# Default values for helm.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1
image:
  repository: "sergant-ua/kbot"
  tag: "v1.0.5-5c00e0f"
  arch: "amd64"
  os: "linux"
secret:
  name: "kbot"
  key: "token"
  env: "TELE_TOKEN"
