# Default values for helm.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: sergantua
  tag: "v1.0.6-185bbaf"
  arch: amd64

secret:
  name: "kbot"
  key: "token"
  env: "TELE_TOKEN"