name: KBOT-CICD

on: push

env:
  REGISTRY: ghcr.io

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest

    permissions:
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Run test
        run: make test
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build&Push
        env:
          APP: "kbot"
          REGISTRY: ${{ env.REGISTRY }}
        run: make image push

